apiVersion: v1
kind: Service
metadata:
  name: springboot3dot5dot9-sandbox
  labels:
    app: springboot3dot5dot9-sandbox
spec:
  type: ClusterIP
  selector:
    app: springboot3dot5dot9-sandbox
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
