# Systemd environment file for the otelcol-contrib service

# Command-line options for the otelcol-contrib service.
# Run `/usr/bin/otelcol-contrib --help` to see all available options.
OTELCOL_OPTIONS="--config=/etc/otelcol-contrib/custom-config.yaml"

DD_API_KEY="your_actual_api_key_here"
DD_SITE="datadoghq.eu"
OTEL_RESOURCE_ATTRIBUTES="datadog.host.name=jek-centos9-v3,deployment.environment=sandbox,service.version=1.2.3"

HTTP_PROXY="http://your-proxy-server:8080"
HTTPS_PROXY="https://your-proxy-server:8080"